// app
#define DEFAULT_TIMEZONE_SHIFT  2*3600
#define DEFAULT_APP_NAME_MAX_LENGTH 20        

// sntp
#define DEFAULT_SNTP_RETRIES    3
#define DEFAULT_SNTP_RETRY_INTERVAL_MS  250

// udp discovery
#define DEFAULT_DISCOVERY_PORT  5001
#define DEFAULT_DISCOVERY_LOOPBACK  0